name: Deploy to GitHub Pages

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

# Permissions nécessaires
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create deployment directory
        run: |
          mkdir -p deploy
          cp *.html deploy/
          cp *.css deploy/
          cp *.js deploy/
          # Exclure secrets.js du déploiement
          rm -f deploy/secrets.js

      - name: Inject secrets into HTML
        run: |
          # Créer le script avec les secrets
          cat > deploy/secrets-inject.js << 'EOF'
          window.GOOGLE_API_KEY = "${{ secrets.GOOGLE_API_KEY }}";
          window.GOOGLE_CLIENT_ID = "${{ secrets.GOOGLE_CLIENT_ID }}";
          window.OPENAI_API_KEY = "${{ secrets.OPENAI_API_KEY }}";
          EOF
          # Remplacer la référence à secrets.js par le script injecté
          sed -i 's|<script src="secrets.js"></script>|<script src="secrets-inject.js"></script>|g' deploy/index.html

      - name: Setup Pages
        uses: actions/configure-pages@v3
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./deploy
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2