name: Deploy to GitHub Pages

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

# Permissions nécessaires
permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Inject secrets into HTML
        run: |
          # Créer un script d'injection des secrets directement dans index.html
          sed -i 's|<script src="secrets.js"></script>|<script>\nwindow.GOOGLE_CLIENT_ID = "${{ secrets.GOOGLE_CLIENT_ID }}";\nwindow.GOOGLE_API_KEY = "${{ secrets.GOOGLE_API_KEY }}";\nwindow.OPENAI_API_KEY = "${{ secrets.OPENAI_API_KEY }}";\n</script>|g' index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          exclude_assets: '.github,README.md,.gitignore'