name: Deploy to GitHub Pages

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

# Permissions nécessaires
permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create deployment directory
        run: |
          mkdir -p deploy
          cp *.html deploy/
          cp *.css deploy/
          cp *.js deploy/
          # Exclure secrets.js du déploiement
          rm -f deploy/secrets.js

      - name: Inject secrets into HTML
        run: |
          # Créer le script avec les secrets
          cat > deploy/secrets-inject.js << 'EOF'
          window.OPENAI_API_KEY = "${{ secrets.OPENAI_API_KEY }}";
          window.SUPABASE_URL = "${{ secrets.SUPABASE_URL }}";
          window.SUPABASE_ANON_KEY = "${{ secrets.SUPABASE_ANON_KEY }}";
          EOF
          # Remplacer la référence à config.js par le script injecté
          sed -i 's|<script src="config.js"></script>|<script src="secrets-inject.js"></script>|g' deploy/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./deploy
          force_orphan: true