name: Deploy to GitHub Pages

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

# Permissions nécessaires
permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create deployment directory
        run: |
          mkdir -p deploy
          cp *.html deploy/
          cp *.css deploy/
          cp *.js deploy/
          # Exclure secrets.js du déploiement
          rm -f deploy/secrets.js

      - name: Inject secrets into HTML
        run: |
          # Remplacer la référence à secrets.js par les vraies valeurs
          sed -i 's|<script src="secrets.js"></script>|<script>\nwindow.GOOGLE_CLIENT_ID = "${{ secrets.GOOGLE_CLIENT_ID }}";\nwindow.GOOGLE_API_KEY = "${{ secrets.GOOGLE_API_KEY }}";\nwindow.OPENAI_API_KEY = "${{ secrets.OPENAI_API_KEY }}";\n</script>|g' deploy/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./deploy
          force_orphan: true