name: Deploy to GitHub Pages

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

# Permissions nécessaires
permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create secrets configuration
        run: |
          cat > secrets.js << EOF
          // Configuration des secrets pour GitHub Pages
          window.GOOGLE_CLIENT_ID = '${{ secrets.GOOGLE_CLIENT_ID }}';
          window.GOOGLE_API_KEY = '${{ secrets.GOOGLE_API_KEY }}';
          window.OPENAI_API_KEY = '${{ secrets.OPENAI_API_KEY }}';
          EOF

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          exclude_assets: '.github,README.md,.gitignore'